name: Trigger Live Preview
on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
  Deploy-to-preview:
    permissions: write-all
    name: Deploy to preview
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Preview this commit at http://ec2-18-116-89-147.us-east-2.compute.amazonaws.com/
