name: Trigger Live Preview
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Deploy-to-preview:
    permissions: write-all
    name: Deploy to preview
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            this should be a comment
